# Generated by Django 4.0.1 on 2022-01-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inside1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('initial', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('std', models.CharField(max_length=2)),
                ('sec', models.CharField(max_length=1)),
                ('bg', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=40)),
                ('max_marks', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subs',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inside1.student')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inside1.subject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inside1.test')),
            ],
        ),
    ]
