# Generated by Django 4.0.1 on 2022-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside1', '0003_test_test_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_class',
            field=models.CharField(default='12', max_length=2),
            preserve_default=False,
        ),
    ]
