# Generated by Django 4.0.1 on 2022-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside1', '0004_test_test_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.CharField(max_length=4),
        ),
    ]
